# Generated by Django 4.2.15 on 2024-08-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='alert_phone_number',
        ),
    ]
