# Generated by Django 4.2.15 on 2024-08-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_booking_alert_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='booking_qr_codes'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qr_codes'),
        ),
    ]
